# Generated by Django 4.1.7 on 2023-03-01 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('team_size', models.IntegerField()),
                ('team_captain', models.CharField(max_length=100)),
                ('division', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
            ],
        ),
    ]
